<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Misfitz_Games</RootNamespace>
    <UserSecretsId>78f07b00-a4f2-41ce-9761-dd926825731a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tiktok-connector\**" />
    <Content Remove="tiktok-connector\**" />
    <EmbeddedResource Remove="tiktok-connector\**" />
    <None Remove="tiktok-connector\**" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="Data\**\*.*" Exclude="Data\**\*.cs">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
	<PackageReference Include="Npgsql" Version="8.0.7" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.0" />
  </ItemGroup>
  
</Project>
